-- DROP TABLE accounts IF EXISTS;

CREATE TABLE accounts (
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    balance DEC(15,2) NOT NULL,
    PRIMARY KEY(id)
);
BEGIN TRANSACTION;-- start a transaction
INSERT INTO accounts(NAME, BALANCE) VALUES ('BOB',1000);
COMMIT;-- insert a new row into the accounts table
SELECT NAME,balance FROM accounts;

BEGIN TRANSACTION;-- start a transaction
INSERT INTO accounts(name,balance)-- insert a new row into the accounts table
VALUES('Alice',10000);
COMMIT;

SELECT NAME,balance FROM accounts;

-- - commit the change (or roll it back later)



-- start a transaction


-- deduct 1000 from account 1
BEGIN;
UPDATE accounts
SET balance = balance+1000
WHERE id = 1;

-- add 1000 to account 2
UPDATE accounts
SET balance = balance + 1000
WHERE id = 2;

-- select the data from accounts
SELECT id, name, balance
FROM accounts;

-- commit the transaction
COMMIT;
--------------------------------------------
-- begin the transaction
BEGIN;

-- deduct the amount from the account 1
UPDATE accounts
SET balance = balance - 1500
WHERE id = 1;
SAVEPOINT my_save_point;
-- add the amount from the account 3 (instead of 2)
UPDATE accounts
SET balance = balance + 1500
WHERE id = 3;
ROLLBACK TO my_save_point;

-- roll back the transaction
ROLLBACK;

